language: node_js
node_js:
  - "0.11"
before_script:
  - npm install grunt-cli -g
  - gem install dpl
after_success:
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then
      dpl --provider=elasticbeanstalk --access-key-id=$AWS_ACCESS_ID --secret-access-key=$AWS_ACCESS_KEY --app="EKM-API" --env="API-dev" --region="us-west-2";
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      dpl --provider=elasticbeanstalk --access-key-id=$AWS_ACCESS_ID --secret-access-key=$AWS_ACCESS_KEY --app="EKM-API" --env="volta-api" --region="us-west-2";
    fi