language: node_js
node_js:
  - "0.11"
before_script:
  - npm install grunt-cli -g
deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_ID
    secret_access_key:
      secure: $AWS_ACCESS_KEY
    region: us-west-2
    app: EKM-API
    env: API-dev
    bucket_name: codeship-volta
    local_dir: Database/dev
    on:
      branch: dev
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_ID
    secret_access_key:
      secure: $AWS_ACCESS_KEY
    region: us-west-2
    app: EKM-API
    env: volta-api
    bucket_name: codeship-volta
    local_dir: Database/master
    on:
      branch: master