module.exports = function( sequelize, DataTypes ) {
  var EKMreading = sequelize.define('EKMreading', {
    id: {
          type: DataTypes.INTEGER,
          autoIncrement: true,
          primaryKey: true
        },
    meterSN: DataTypes.STRING,
    Group: DataTypes.INTEGER,
    Interval: DataTypes.INTEGER,
    Protocol: DataTypes.STRING,
    MAC_Addr: DataTypes.STRING,
    Date: DataTypes.DATE,
    Time: DataTypes.DATE,
    Time_Stamp_UTC_ms: DataTypes.DATE,
    Firmware: DataTypes.STRING,
    // had to rename Model to meterModel
    // because it didn't like Model for import
    // even as a string
    meterModel: DataTypes.STRING,
    kWh_Tot: DataTypes.STRING,
    kWh_Tariff_1: DataTypes.STRING,
    kWh_Tariff_2: DataTypes.STRING,
    kWh_Tariff_3: DataTypes.STRING,
    kWh_Tariff_4: DataTypes.STRING,
    Rev_kWh_Tot: DataTypes.STRING,
    Rev_kWh_Tariff_1: DataTypes.STRING,
    Rev_kWh_Tariff_2: DataTypes.STRING,
    Rev_kWh_Tariff_3: DataTypes.STRING,
    Rev_kWh_Tariff_4: DataTypes.STRING,
    RMS_Volts_Ln_1: DataTypes.STRING,
    RMS_Volts_Ln_2: DataTypes.STRING,
    RMS_Volts_Ln_3: DataTypes.STRING,
    Amps_Ln_1: DataTypes.STRING,
    Amps_Ln_2: DataTypes.STRING,
    Amps_Ln_3: DataTypes.STRING,
    RMS_Watts_Ln_1: DataTypes.STRING,
    RMS_Watts_Ln_2: DataTypes.STRING,
    RMS_Watts_Ln_3: DataTypes.STRING,
    RMS_Watts_Tot: DataTypes.STRING,
    Power_Factor_Ln_1: DataTypes.STRING,
    Power_Factor_Ln_2: DataTypes.STRING,
    Power_Factor_Ln_3: DataTypes.STRING,
    RMS_Watts_Max_Demand: DataTypes.STRING,
    Max_Demand_Period: DataTypes.STRING,
    CT_Ratio: DataTypes.STRING,
    Pulse_Cnt_1: DataTypes.STRING,
    Pulse_Cnt_2: DataTypes.STRING,
    Pulse_Cnt_3: DataTypes.STRING,
    Pulse_Ratio_1: DataTypes.STRING,
    Pulse_Ratio_2: DataTypes.STRING,
    Pulse_Ratio_3: DataTypes.STRING,
    State_Inputs: DataTypes.STRING,
    Reactive_Energy_Tot: DataTypes.STRING,
    kWh_Rst: DataTypes.STRING,
    Rev_kWh_Rst: DataTypes.STRING,
    Reactive_Pwr_Ln_1: DataTypes.STRING,
    Reactive_Pwr_Ln_2: DataTypes.STRING,
    Reactive_Pwr_Ln_3: DataTypes.STRING,
    Reactive_Pwr_Tot: DataTypes.STRING,
    kWh_Scale: DataTypes.STRING,
    Line_Freq: DataTypes.STRING,
    State_Watts_Dir: DataTypes.STRING,
    State_Out: DataTypes.STRING,
    kWh_Ln_1: DataTypes.STRING,
    kWh_Ln_2: DataTypes.STRING,
    kWh_Ln_3: DataTypes.STRING,
    Rev_kWh_Ln_1: DataTypes.STRING,
    Rev_kWh_Ln_2: DataTypes.STRING,
    Rev_kWh_Ln_3: DataTypes.STRING,
    CF_Ratio: DataTypes.STRING
  });
    
    return EKMreading;
    // stationId added as foreign key
};
